DROP TABLE IF EXISTS T_ROLE;
CREATE TABLE T_ROLE (
	ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL
) ENGINE = INNODB DEFAULT CHARSET = LATIN1;

DROP TABLE IF EXISTS T_USER;
CREATE TABLE T_USER (
	ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL
) ENGINE = INNODB DEFAULT CHARSET = LATIN1;

DROP TABLE IF EXISTS T_USER_ROLE;
CREATE TABLE T_USER_ROLE (
	ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	USER_ID INT(11) REFERENCES T_USER (ID),
	ROLE_ID INT(11) REFERENCES T_ROLE (ID)
) ENGINE = INNODB DEFAULT CHARSET = LATIN1;

DROP TABLE IF EXISTS T_USER_DETAIL;
CREATE TABLE T_USER_DETAIL (
	ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	EMAIL_ADDRESS VARCHAR(100) NOT NULL,
	MOBILE_NUMBER BIGINT NOT NULL
) ENGINE = INNODB DEFAULT CHARSET = LATIN1;

DROP TABLE IF EXISTS T_CATEGORY;
CREATE TABLE T_CATEGORY (
	ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL
) ENGINE = INNODB DEFAULT CHARSET = LATIN1;

DROP TABLE IF EXISTS T_PRODUCT;
CREATE TABLE T_PRODUCT (
	ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(100) NOT NULL,
	CATEGORY_ID INT(11) REFERENCES T_CATEGORY (ID)
) ENGINE = INNODB DEFAULT CHARSET = LATIN1;

DROP TABLE IF EXISTS T_CATALOG;
CREATE TABLE T_CATALOG (
	ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL
) ENGINE = INNODB DEFAULT CHARSET = LATIN1;

DROP TABLE IF EXISTS T_CATALOG_PRODUCT;
CREATE TABLE T_CATALOG_PRODUCT (
	ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	PRODUCT_ID INT(11) REFERENCES T_PRODUCT (ID),
	CATALOG_ID INT(11) REFERENCES T_CATALOG (ID),
	QUANTITY INT(11) NOT NULL,
	PRICE INT(11) NOT NULL
) ENGINE = INNODB DEFAULT CHARSET = LATIN1;

DROP TABLE IF EXISTS T_COUNTRY;
CREATE TABLE T_COUNTRY (
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT, 
    NAME VARCHAR(50) NOT NULL, 
    ISD VARCHAR(20) NOT NULL
) ENGINE = INNODB DEFAULT CHARSET = LATIN1;

DROP TABLE IF EXISTS T_LOCATION;
CREATE TABLE T_LOCATION (
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT, 
    NAME VARCHAR(50), 
    PIN INT(11), 
    CITY VARCHAR(50), 
    STATE VARCHAR(50),
    COUNTRY_ID INT(11) REFERENCES T_COUNTRY (ID)
) ENGINE = INNODB DEFAULT CHARSET = LATIN1;

DROP TABLE IF EXISTS T_DELIVERY_LOCATION;
CREATE TABLE T_DELIVERY_LOCATION (
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    VALUE_1 VARCHAR(50) NOT NULL,
    VALUE_2 VARCHAR(50) NOT NULL,
    VALUE_3 VARCHAR(50) NULL,
    LOCATION_ID INT(11) REFERENCES T_LOCATION (ID)
) ENGINE = INNODB DEFAULT CHARSET = LATIN1;

DROP TABLE IF EXISTS T_USER_ORDER;
CREATE TABLE T_USER_ORDER (
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    USER_ID INT(11) REFERENCES T_USER_DETAIL (ID),
    STATUS VARCHAR(20) NOT NULL,
    DELIVERY_STATUS VARCHAR(20) NOT NULL,
    DRAFTED_DATE DATE NOT NULL,
    ORDERED_DATE DATE NOT NULL,
    CANCELLED_DATE DATE NOT NULL
) ENGINE = INNODB DEFAULT CHARSET = LATIN1;

DROP TABLE IF EXISTS T_USER_ORDERED_ITEM;
CREATE TABLE T_USER_ORDERED_ITEM (
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    USER_ORDER_ID INT(11) REFERENCES T_USER_ORDER (ID),
    PRODUCT_ID INT(11) REFERENCES T_PRODUCT (ID),
    QUANTITY INT(11) NOT NULL,
	PRICE INT(11) NOT NULL
) ENGINE = INNODB DEFAULT CHARSET = LATIN1;

DROP TABLE IF EXISTS T_USER_ORDER_DELIVERY_LOCATION;
CREATE TABLE T_USER_ORDER_DELIVERY_LOCATION (
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    USER_ORDER_ID INT(11) REFERENCES T_USER_ORDER (ID),
    DELIVERY_LOCATION_ID INT(11) REFERENCES T_DELIVERY_LOCATION (ID)
) ENGINE = INNODB DEFAULT CHARSET = LATIN1;
