server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: catalog-service
spring:
  profiles: development
spring:
  profiles:
    active: development
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/