server:
  port: 9999
spring:
  application:
    name: proxy-server
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    oauth2-server: /oauth2/**
    catalog-service: /catalog/**
    inventory-service: /inventory/**
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8181/secure/user
  ignored: /catalog/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/