server:
  port: 9999
spring:
  application:
    name: proxy-server
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    catalog-service: /catalog/**
    inventory-service: /inventory/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/