server:
  port: 9999
spring:
  application:
    name: proxy
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    user: /user/**
    catalog: /catalog/**
    inventory: /inventory/**