server:
  port: 8787
spring:
  application:
    name: front-gui
  datasource:
    url: jdbc:hsqldb:hsql://localhost
    initialize: true
zuul:
  routes:
    user-service: 
      path: /api/userservice/**