server:
  port: 8787
spring:
  application:
    name: web-server
zuul:
  ignored-services: '*'
  routes:
    proxy-server:
      path: /api/**
      url: http://localhost:9999
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/