server:
  port: ${PORT:${SERVER_PORT:46357}}
---
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:hsqldb:hsql://localhost
    initialize: true
  profiles:
    active: development
---
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/farm
    initialize: true
    username: root
    password: root
  profiles:
    active: production
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update