server:
  port: ${PORT:${SERVER_PORT:46357}}
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:hsqldb:hsql://localhost
    initialize: true
    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update 