server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:hsqldb:hsql://localhost
    initialize: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/