INSERT INTO T_ROLE (ID, NAME) VALUES (1, 'ROLE_USER');
INSERT INTO T_ROLE (ID, NAME) VALUES (2, 'ROLE_ADMIN');
INSERT INTO T_USER (ID, USER_NAME, USER_PASS) VALUES (1, 'admin', 'admin');
INSERT INTO T_USER_ROLE (ID, USER_ID, ROLE_ID) VALUES (1, 1, 1);
INSERT INTO T_USER_ROLE (ID, USER_ID, ROLE_ID) VALUES (2, 1, 2);
INSERT INTO T_USER (ID, USER_NAME, USER_PASS) VALUES (2, 'user', 'user');
INSERT INTO T_USER_ROLE (ID, USER_ID, ROLE_ID) VALUES (3, 2, 1);