spring:
  application:
    name: eureka-server
server:
  port: 8761
management:
  context-path: /admin
eureka:
  instance:
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
  server:
    waitTimeInMsWhenSyncEmpty: 0
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/ 