INSERT INTO T_ROLE (ID, NAME) VALUES (1, 'ROLE_USER');
INSERT INTO T_ROLE (ID, NAME) VALUES (2, 'ROLE_ADMIN');
INSERT INTO T_USER (ID, USERNAME, PASSWORD) VALUES (1, 'yorkfarmadmin', 'yorkfarmadmin');
INSERT INTO T_USER_ROLE (ID, USER_ID, ROLE_ID) VALUES (1, 1, 1);
INSERT INTO T_USER_ROLE (ID, USER_ID, ROLE_ID) VALUES (2, 1, 2);