/**
    York Farm SQL Script (Date:- Sep 20 2016)
    Created By Sivakumar.AKURATI/Raghu.CHOWDAREDDY
*/

DROP DATABASE IF EXISTS YORK_FARM;
CREATE DATABASE YORK_FARM;
USE YORK_FARM;

DROP TABLE IF EXISTS T_ROLE;
CREATE TABLE T_ROLE (
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS T_USER;
CREATE TABLE T_USER (
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(20) NOT NULL
);

DROP TABLE IF EXISTS T_USER_ROLE;
CREATE TABLE T_USER_ROLE (
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    USER_ID INT(11) REFERENCES T_USER(ID),
    ROLE_ID INT(11) REFERENCES T_ROLE(ID)
);

DROP TABLE IF EXISTS T_COUNTRY;
CREATE TABLE T_COUNTRY (
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    ISD_CODE VARCHAR(10) NOT NULL
);

DROP TABLE IF EXISTS T_LOCATION;
CREATE TABLE T_LOCATION (
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    STATE_NAME VARCHAR(50) NOT NULL,
    CITY_NAME VARCHAR(50) NOT NULL,
    ZIP_CODE INT(11) NOT NULL,
    COUNTRY_ID INT(11) REFERENCES T_COUNTRY(ID)
);

DROP TABLE IF EXISTS T_ADDRESS;
CREATE TABLE T_ADDRESS (
	ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	VALUE_1 VARCHAR(50) NOT NULL,
	VALUE_2 VARCHAR(50) NOT NULL,
	VALUE_3 VARCHAR(50) NULL,
	LOCATION_ID INT(11) REFERENCES T_LOCATION(ID)
);

DROP TABLE IF EXISTS T_CATEGORY;
CREATE TABLE T_CATEGORY (
	ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS T_PRODUCT;
CREATE TABLE T_PRODUCT (
	ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	DESCRIPTION VARCHAR(500) NOT NULL,
	PRICE DECIMAL(2) NOT NULL,
	IS_STOCK TINYINT NOT NULL,
	CATEGORY_ID INT(11) REFERENCES T_CATEGORY(ID)
);

DROP TABLE IF EXISTS T_CATALOG;
CREATE TABLE T_CATALOG (
	ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL
);

DROP TABLE IF EXISTS T_CATALOG_PRODUCT;
CREATE TABLE T_CATALOG_PRODUCT (
	ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	CATALOG_ID INT(11) REFERENCES T_CATALOG(ID),
	PRODUCT_ID INT(11) REFERENCES T_PRODUCT(ID)
);