server:
  port: 8181
  contextPath: /secure
spring:
  application:
    name: outh2-server
security:
  user:
    password: password
  enable-csrf: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/